# Generated by Django 3.1.2 on 2020-10-13 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201013_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField()),
                ('contact_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="contact number must be entered in the format: '9999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10,10}$')])),
                ('address', models.CharField(max_length=250)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
